name: Quark签到

on:
  schedule:
    - cron: '1 0 * * *'    # 北京时间 08:00 (UTC+8 -> UTC+1)
    - cron: '1 11 * * *'   # 北京时间 19:00 (UTC+8 -> UTC+5)
  workflow_dispatch:       # 允许手动触发

jobs:
  sign-in:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 随机延迟（早上）
        if: github.event.schedule == '0 1 * * *'
        run: |
          delay=$((RANDOM % 60))
          echo "早上签到，延迟 $delay 秒后开始.."
          sleep $delay

      - name: 随机延迟（下午/手动触发）
        if: github.event.schedule == '0 5 * * *' || github.event_name == 'workflow_dispatch'
        run: |
          delay=$((RANDOM % 30))
          echo "下午兜底或手动触发，延迟 $delay 秒后开始.."
          sleep $delay

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests

      - name: 执行签到脚本
        env:
          # 确保这些变量已在你的GitHub仓库Secrets中设置
          COOKIE_QUARK: ${{ secrets.COOKIE_QUARK }}
          WXPUSHER_APP_TOKEN: ${{ secrets.WXPUSHER_APP_TOKEN }} # <-- 新增行
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}             # <-- 新增行
        run: python checkIn_Quark.py

      - name: 空提交保持活跃
        if: success() && github.event_name == 'schedule'
        run: |
          git config --local user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}
          git pull --rebase --autostash
          git commit --allow-empty -m "CHORE: 保持运行.."
          git push

      - name: 清理旧的工作流记录
        uses: yxdz2020/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 10
